name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Isometric Contribution Graph
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: guruvishnuk
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: profile-3d-contrib.svg
          output_action: commit
          committer_branch: output
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "chore: update 3D isometric contribution graph"
